### ISSUE TITLE
Kein ACPI shutdown unter Proxmox möglich

### ISSUE THREAD

**Issue by ThorstenGTV** [AuxXxilium/arc-automated#2]
Hallo zusammen, ich habe die aktuelle release unter Proxmox erfolgreich installiert. Auch virtio SCSI Disks werden problemlos erkannt auch die virtio NIC alles super. Leider scheint das ACPI showdown zumindest bei mir nicht zu funktionieren. Wäre klasse wenn sich das mal jemand anschauen könnte. Viele Grüße Toti

**Comment by ThorstenGTV** [comment]
> Hallo zusammen, ich habe die aktuelle release unter Proxmox erfolgreich installiert. Auch virtio SCSI Disks werden problemlos erkannt auch die virtio NIC alles super. Leider scheint das ACPI showdown zumindest bei mir nicht zu funktionieren. Wäre klasse wenn sich das mal jemand anschauen könnte. Viele Grüße Toti

....sorry nach einem Reboot geht's dann doch!

**Comment by AuxXxilium** [comment]
Ok danke für das Feedback. Haben aktuell mit ein paar Problemen zu kämpfen. Sobald wir die behoben haben, kommt auch eine neue Version vom Automated.
